version: '3.8'
services:
  mongo:
    container_name: docker_mongo
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=younes
      - MONGO_INITDB_ROOT_PASSWORD=younes
    volumes:
      - db:/data/db
  app:
    depends_on:
      - mongo
    container_name: docker_node
    restart: always
    build: .
    ports:
      - '80:3000'
    stdin_open: true
    tty: true

volumes:
  db: